


#ifndef CUDA_NOTEBOOK_CONVOLUTIONAL_NEURAL_NETWORK_CUH
#define CUDA_NOTEBOOK_CONVOLUTIONAL_NEURAL_NETWORK_CUH


class convolutional_neural_network {

};


#endif //CUDA_NOTEBOOK_CONVOLUTIONAL_NEURAL_NETWORK_CUH
