


#ifndef CUDA_NOTEBOOK_GENERATIVE_ADVERSARIAL_NETWORK_CUH
#define CUDA_NOTEBOOK_GENERATIVE_ADVERSARIAL_NETWORK_CUH


class generative_adversarial_network {

};


#endif //CUDA_NOTEBOOK_GENERATIVE_ADVERSARIAL_NETWORK_CUH
